MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64
  WEIGHTED_NORM: True
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'HALO'
  RATIO: 1.
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  NAME: 'hyper_v3plus_64_WN_fully_sup'
  GROUP: 'source_target'
  ENTITY: 'pinlab-sapienza'
resume: 'results/pretrain_synthia/CHECKPOINT_PATH.ckpt'
OUTPUT_DIR: 'results/source_target_synthia/OUTPUT_PATH'
DEBUG: 0
PROTOCOL: 'fully_sup'
