MODEL:
  NAME: "deeplabv3plus_resnet101"
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64
  HFR: True
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  BATCH_SIZE: 2
ACTIVE:
  BUDGET: 1.
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  GROUP: 'source_target'
  ENTITY: 'pinlab-sapienza'
NAME: 'hyper_v3plus_fully_sup'
resume: 'results/pretrain_synthia/CHECKPOINT_PATH.ckpt'
OUTPUT_DIR: 'results/source_target_synthia/OUTPUT_PATH'
DEBUG: False
PROTOCOL: 'fully_sup'
