MODEL:
  NAME: "deeplabv3plus_resnet101"
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64
  HFR: True
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3]
  BATCH_SIZE: 2
  BASE_LR: 1e-3
  NUM_ITER: 60000
  WARMUP_ITERS: 600
WANDB:
  ENABLE: True
  GROUP: 'synthia_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'
NAME: 'hyper_v3plus'
OUTPUT_DIR: 'results/pretrain_synthia/OUTPUT_PATH'
PROTOCOL: 'source'
