MODEL:
  NAME: "deeplabv3plus_resnet101"   #  deeplabv2_resnet101 or deeplabv3plus_resnet101
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64
  WEIGHTED_NORM: True
DATASETS:
  SOURCE_TRAIN: "synthia_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  # GPUS: [0,1,2,3]
  GPUS: [4,5,6,7]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  CHECKPOINT_PERIOD: 5000
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'AL-RIPU'
  SETTING: 'RA'
  SELECT_ITER: [0, 15001, 30001, 40001, 50001]   # [0, 10001, 15001, 20001, 25001] or [0, 15001, 30001, 40001, 50001]
  RATIO: 0.05     # 0.022  or  0.05  or  1.
  RADIUS_K: 1      # smaller might be better
  UNCERTAINTY: 'entropy'   # 'entropy' or 'hyperbolic' or 'certainty' or 'none'
  PURITY: 'hyper'             # 'ripu' or 'hyper' or 'none'
  VIZ_MASK: True
  NORMALIZE: True
  WEIGHT_UNCERT: [0.2, 0.2, 0.35, 0.35, 0.5]
  MASK_RADIUS_K: 5
  K: 100
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  NAME: 'hyper_dlv3_64_WN_5_perc_entr_hyperimp_K200_RK5'
  GROUP: 'source_free'
  ENTITY: 'pinlab-sapienza'
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
TEST:
  BATCH_SIZE: 1
resume: 'results/pretrain_synthia/hyper_v3plus_ch_64_WN/model.ckpt'
OUTPUT_DIR: 'results/source_free/hyper_dlv3_64_WN_5_perc_entr_hyperimp_K100_RK5'
DEBUG: 0
PROTOCOL: 'source_free'