MODEL:
  NAME: "deeplabv3plus_resnet101"   #  deeplabv2_resnet101 or deeplabv3plus_resnet101
  NUM_CLASSES: 16
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
  HFR: True
DATASETS:
  TEST: "cityscapes_val"
INPUT:
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0]
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
  SAVE_EMBED: False
  BATCH_SIZE: 1
resume: 'results/source_target_synthia/CHECKPOINT_PATH.ckpt'
OUTPUT_DIR: 'results/source_target_synthia/OUTPUT_PATH'
DEBUG: 0