MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  HYPER: False
  REDUCED_CHANNELS: 256
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  BATCH_SIZE: 2
  BASE_LR: 1e-3
  MAX_ITER: 31250
  STOP_ITER: 20000
WANDB:
  ENABLE: True
  NAME: 'deeplabv3plus_resnet101'
  GROUP: 'gtav_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'