MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0, 1, 2, 3]
  BASE_LR: 1e-3
  NUM_ITER: 30000
  CHECKPOINT_PERIOD: 1000
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'AL-RIPU'
  SETTING: 'RA'
  SELECT_ITER: [0, 10001, 15001, 20001, 25001]
  RATIO: 0.022
  RADIUS_K: 1  # smaller might be better
  UNCERTAINTY: 'hyperbolic' # 'entropy' or 'hyperbolic' or 'certainty' or 'none'
  PURITY: 'ripu'            # 'ripu' or 'none'
  VIZ_MASK: True
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  NAME: 'dlv3plus_RA_hyper_ripu_unc_64'
  GROUP: 'source_free'
  ENTITY: 'pinlab-sapienza'
TEST:
  VIZ_SCORE: True
  VIZ_WRONG: True
TEST:
  BATCH_SIZE: 1
resume: 'results/pretrain_gtav/hyper_v3plus_64/model_iter020000.pth'
OUTPUT_DIR: 'results/source_free/dlv3plus_RA_hyper_ripu_unc_64'
DEBUG: 0
