MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [4,5,6,7]      # [0,1,2,3] or [4,5,6,7]
  # EPOCHS: 30
  BASE_LR: 1e-3
  NUM_ITER: 30000
  STOP_ITER: 30000
  CHECKPOINT_PERIOD: 1000
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'AL-RIPU1'
  SETTING: 'RA'
  SELECT_ITER: [0, 10001, 15001, 20001, 25001]
  # SELECT_EPOCH: [0, 10, 15, 20, 25]
  RATIO: 0.022
  RADIUS_K: 1  # smaller might be better
  UNCERTAINTY: 'hyperbolic' # 'entropy' or 'hyperbolic' or 'certainty' or 'none'
  PURITY: 'none'            # 'ripu' or 'none'
  VIZ_MASK: False
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  NAME: 'dlv3_RA_hyper_hypunc_only_ch64'
  GROUP: 'source_free'
  ENTITY: 'pinlab-sapienza'
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
TEST:
  BATCH_SIZE: 1
resume: "checkpoints/pretrain_gtav_hyper_dlv3_64/model_iter020000.pth"
OUTPUT_DIR: 'results/source_free/dlv3_RA_hyper_hypunc_only_ch64'
DEBUG: 0
