MODEL:
  NAME: "deeplabv2_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 256
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  BATCH_SIZE: 4
  BASE_LR: 1e-3
  MAX_ITER: 31250
  STOP_ITER: 20000
WANDB:
  ENABLE: True
  NAME: 'deeplabv2_resnet101_hyper_ch_${MODEL.REDUCED_CHANNELS}'
  GROUP: 'gtav_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'
ACTIVE:
  UNCERTAINTY: 'hyperbolic' # 'entropy' or 'hyperbolic' or 'none'
  PURITY: 'ripu'            # 'ripu' or 'none'