MODEL:
  NAME: "deeplabv2_resnet101"
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 256
DATASETS:
  SOURCE_TRAIN: "cityscapes_train"  # "gtav_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3]
  BATCH_SIZE: 2 # 4
  BASE_LR: 1e-3
  MAX_ITER: 60000 # 31250
  STOP_ITER: 60000 # 20000
WANDB:
  ENABLE: True
  NAME: 'dlv2_hyper_fully_supervised'
  GROUP: 'gtav_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'
resume: "checkpoints/pretrain_gtav_hyper/model_iter020000.pth"
OUTPUT_DIR: 'results/source_free/dlv2_hyper_fully_supervised'