MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [4,5,6,7]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  CHECKPOINT_PERIOD: 400
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'AL-RIPU'
  SETTING: 'RA'
  SELECT_ITER: [0]
  RATIO: 1.    # 0.022
  RADIUS_K: 1  # smaller might be better
  UNCERTAINTY: 'entropy' # 'entropy' or 'hyperbolic' or 'certainty' or 'none'
  PURITY: 'ripu'            # 'ripu' or 'none'
  VIZ_MASK: False
WANDB:
  ENABLE: False
  PROJECT: 'active_domain_adapt'
  NAME: 'hyper_v3plus_RA_ripu_64_60k_fully_supervised'
  GROUP: 'source_target'
  ENTITY: 'pinlab-sapienza'
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
TEST:
  BATCH_SIZE: 1
resume: 'results/pretrain_gtav/hyper_v3plus_64/model_iter020000.pth'
# checkpoint: 'results/source_target/hyper_v3plus_RA_ripu_64/epoch=0-step=20000.ckpt'
OUTPUT_DIR: 'results/source_target/hyper_v3plus_RA_ripu_64_60k_fully_supervised'
DEBUG: 0
PROTOCOL: 'source_target'   # source | source_target | source_free
