MODEL:
  NAME: "deeplabv3plus_resnet101"   #  deeplabv2_resnet101 or deeplabv3plus_resnet101
  HYPER: False
  REDUCED_CHANNELS: 512
  HFR: False
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0,1,2,3]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  BATCH_SIZE: 2
  CONSISTENT_LOSS: 0.1
ACTIVE:
  SELECT_ITER: [0, 15000, 30000, 40000, 50000]
  BUDGET: 0.05
  UNCERTAINTY: 'entropy'
  PURITY: 'ripu'
  VIZ_MASK: False
  NORMALIZE: False
  MASK_RADIUS_K: 3
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  GROUP: 'source_target'
  ENTITY: 'pinlab-sapienza'
NAME: 'ripu_v3plus_5perc'
resume: 'results/pretrain_gtav/CHECKPOINT_PATH.ckpt'
OUTPUT_DIR: 'results/source_target/OUTPUT_PATH'
DEBUG: 0
PROTOCOL: 'source_target'   # source | source_target | source_free
