MODEL:
  NAME: "segformer_b4"   # deeplabv3plus_resnet101
  WEIGHTS: 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth'
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64
  HFR: True
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [4,5,6,7]
  BATCH_SIZE: 2
  BASE_LR: 1e-5
  OPTIM: "adam"
  SCHEDULER: "constant"
  NUM_ITER: 60000
  WARMUP_ITERS: 600
WANDB:
  ENABLE: True
  NAME: 'cityscapes_pretrain'
  GROUP: 'gtav_pretraining'
  PROJECT: 'active_domain_adapt'
  ENTITY: 'pinlab-sapienza'
NAME: 'halo_gta_pretrain_segformer_b4_fixed_lr'
OUTPUT_DIR: 'results/pretrain_gtav/'
PROTOCOL: 'source'