MODEL:
  NAME: "deeplabv2_resnet101"   #  deeplabv2_resnet101 or deeplabv3plus_resnet101
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64
  HFR: True
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [4,5,6,7]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  BATCH_SIZE: 2
ACTIVE:
  NAME: 'HALO'
  SETTING: 'RA'
  SELECT_ITER: [0, 15000, 30000, 40000, 50000]
  BUDGET: 0.022
  RADIUS_K: 1
  UNCERTAINTY: 'entropy'
  PURITY: 'radius'
  VIZ_MASK: False
  NORMALIZE: True
  MASK_RADIUS_K: 5
  K: 100
WANDB:
  ENABLE: True
  PROJECT: 'active_domain_adapt'
  GROUP: 'source_free'
  ENTITY: 'pinlab-sapienza'
NAME: 'halo_v2_radius_entropy_2perc'
resume: 'results/pretrain_gtav/hyper_v2_ch_64/model_global_step=27998.0_mIoU=36.12.ckpt'
OUTPUT_DIR: 'results/source_free/'
DEBUG: 0
PROTOCOL: 'source_free'