MODEL:
  NAME: "deeplabv3plus_resnet101"   #  deeplabv2_resnet101 or deeplabv3plus_resnet101
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64
  WEIGHTED_NORM: True
DATASETS:
  SOURCE_TRAIN: "gtav_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  # GPUS: [0,1,2,3]
  GPUS: [4,5,6,7]
  BASE_LR: 1e-3
  NUM_ITER: 60000
  CHECKPOINT_PERIOD: 5000
  BATCH_SIZE: 1
  CONSISTENT_LOSS: 0.
ACTIVE:
  NAME: 'AL-RIPU'
  SETTING: 'RA'
  SELECT_ITER: [0, 15001, 30001, 40001, 50001]   # [0, 10001, 15001, 20001, 25001] or [0, 15001, 30001, 40001, 50001]
  RATIO: 0.05     # 0.022  or  0.05  or  1.
  RADIUS_K: 1      # smaller might be better
  UNCERTAINTY: 'hyperbolic'   # 'entropy' or 'hyperbolic' or 'certainty' or 'none'
  PURITY: 'hyper'             # 'ripu' or 'hyper' or 'none'
  VIZ_MASK: True
  NORMALIZE: True
  WEIGHT_UNCERT: [1., .9, .7, .5, .3]
  MASK_RADIUS_K: 5
  K: 100
  QUANT: 'uniform'
WANDB:
  ENABLE: False
  PROJECT: 'active_domain_adapt'
  NAME: 'hyper_dlv3_64_WN_5_perc_hyperimp_hyperunc'
  GROUP: 'source_target'
  ENTITY: 'pinlab-sapienza'
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
TEST:
  BATCH_SIZE: 1
resume: 'results/pretrain/hyper_v3plus_ch_64_WN/model_global_step=25998.0_mIoU=38.99.ckpt'
OUTPUT_DIR: 'results/source_target/hyper_dlv3_64_WN_5_perc_hyperimp_hyperunc'
DEBUG: 0
PROTOCOL: 'source_target'   # source | source_target | source_free
