MODEL:
  NAME: "deeplabv3plus_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
  WEIGHTED_NORM: True
DATASETS:
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1280, 720)
  TARGET_INPUT_SIZE_TRAIN: (1280, 640)
  INPUT_SIZE_TEST: (1280, 640)
ACTIVE:
  NAME: 'HALO'
SOLVER:
  GPUS: [0]
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
  SAVE_EMBED: False
  BATCH_SIZE: 1
resume: 'results/source_target/CHECKPOINT_PATH.ckpt'
OUTPUT_DIR: 'results/source_target/OUTPUT_PATH'
DEBUG: 0