MODEL:
  NAME: "deeplabv3plus_resnet101"   # deeplabv2_resnet101 or deeplabv3plus_resnet101
  HYPER: True
  REDUCED_CHANNELS: 64      # 256 or 10
  HFR: True
DATASETS:
  TEST: "cityscapes_val"
INPUT:
  INPUT_SIZE_TEST: (1280, 640)
SOLVER:
  GPUS: [0]
TEST:
  VIZ_SCORE: False
  VIZ_WRONG: False
  SAVE_EMBED: False
  BATCH_SIZE: 1
NAME: 'halo_v3plus_radius_entropy_5perc'
resume: 'results/source_target/CKPT_PATH.pth'
OUTPUT_DIR: 'results/source_target/'
DEBUG: False